###
GET http://localhost:8080/
Content-Type: application/json

###

POST http://localhost:8080/departments
Content-Type: application/json

{
    "departmentName":"" ,
    "departmentAddress":"Italy",
    "departmentCode":"ITIT"
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
    "departmentName":"Accounting",
    "departmentAddress":"Canada",
    "departmentCode":"ACC"
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
    "departmentName":"Health",
    "departmentAddress":"Hungary",
    "departmentCode":"HHH"
}


###
GET http://localhost:8080/departments/1
Content-Type: application/json

###
GET http://localhost:8080/departments/1
Content-Type: application/json

###
GET http://localhost:8080/departments/name/Health
Content-Type: application/json

###
GET http://localhost:8080/departments/name/health
Content-Type: application/json

###
PUT http://localhost:8080/departments/2
Content-Type: application/json

{
    "departmentName":"AccountingEdited",
    "departmentCode":"ACCEd"
}

###
GET http://localhost:8080/
Content-Type: application/json


###
DELETE  http://localhost:8080/departments/1
Content-Type: application/json